### ISSUE TITLE
No validation error on await on non-async function call

### ISSUE THREAD

**Issue by NumberFourAG** [NumberFour/n4js#115]
IDEBUG-843

```
class C {}
function bar(): C { return null }
async function foo() {
    // XPECT FIXME errors --> "bar is not an async function"
    await bar();
} 
```

**Comment by mor-n4** [comment]
I think at some point during the discussion of async/await for ES7 it was defined as legal to use await on any value, in particcular a non-Promise value (iirc). If this is (still) true, we should not add such an error as proposed in the task description (maybe a warning instead).

**Comment by mor-n4** [comment]
only make it a warning (it's not illegal - but double check ES spec)

**Comment by JensN4** [comment]
cf. 
- Spec: https://tc39.github.io/ecmascript-asyncawait/
- Impl: https://github.com/tc39/ecmascript-asyncawait
- Comment: http://www.2ality.com/2016/02/async-functions.html

**Comment by mmews-n4** [comment]
I installed the [prototype](https://github.com/tc39/ecmascript-asyncawait) that transforms the Async/Await-feature to vanilla ES5, so that is can be used in Node. In the following example, the `await` keyword was toggled (in the marked line). The resulting code was affected by this change, as if the addition was an asynchronous expression. Thus, I think it is momentarily safe to say that the `await` construct accepts non-async expressions.

```
async function foo() { 
    return "World"; 
}; 
async function bar() { 
    var i = await (7 + 2); // toggled 'await' here
    var s = await (foo());
    return "Hello " + s; 
}; 
```

**Comment by mmews-n4** [comment]
Note: The HighlightingParser.java file was adjusted so that it now also highlights the keyword 'await'.
