### ISSUE TITLE
Spec ctor not initializing inherited fields

### ISSUE THREAD

**Issue by dbo** [NumberFour/n4js#151]
Consider the following code:

``` js
class A {
    public num: number;
}

class B extends A {
    public foo: string;

    public constructor(@Spec spec: ~i~this) {}
}

new B({
    num: 5,
    foo: "ff"
})
```

Either the generated code is missing initialization of `A.num` in ctor of `B` or the above should not validate.

**Comment by JensN4** [comment]
Actually this is not really a bug, since it is according to the spec (Constraints 54). But I agree, the result is unexpected, so we have to change both, spec and implementation.

But what do we want? 
- Should we simply disallow spec-style constructor in a subclass which superclass provides public fields but no spec-style constructor? 
- Or just add a warning that public fields of super classes will not be initialized automatically? (And resolve that warning either by providing a spec-style ctor in super class or explicitly assigning it in the code -- which would be hard to analyse)
- Initialize public fields declared in super classes w/p spec-style ctor automatically?

But:
- Since num is not final, there is no need to initialize it. So, the current behavior is fine. I mean, if you just initialize an A, num is not initialized either.

I would vote for the following solution: If a subclass introduces a spec-style constructor and the superclass has no spec-style, constructor, then all inherited public fields have to be either
- manually set by the user or
- used as arguments in the super call (e.g. (super(spec.num)).

Otherwise, a warning will be created.

**Comment by JensN4** [comment]
Note that we have to adjust the super-call validation to ECMAScript 2015 anyway. (see IDE-1914)

**Comment by JensN4** [comment]
Changed type from bug to enhancement.

@dbo Could you give me some feedback about what you think about that issue and my proposal?

Actually, I'm not quite sure if the proposal is so great. At least we would need '@SuppresWarnings', otherwise it would be annoying.

**Comment by dbo** [comment]
I'd vote for your second option, i.e. leave the current generated code as is, BUT enforce that the developer has to call the `super()` ctor explicitly. That way we make sure she knows about the initialization that takes place, which would be default construction (w/o spec behaviour) in the given example.

Additionally, I'd suggest to emit a warning about `num` being not taken for initialzation as well, like we already do for unhandled spec fields.

**Comment by mmews-n4** [comment]
continued here https://github.com/eclipse/n4js/issues/593
