### ISSUE TITLE
Revise Browse-Buttons in Wizard-Dialogs.

### ISSUE THREAD

**Issue by torstenkraemer** [NumberFour/n4js#157]
Detected while working in GH-155. The underlying functionality of the Browsing-functionality is not compatible with the actual Dialog model. 
For instance the Browse source folders creates a tree-based interface. The filter for this interface is configured to allow only concrete source-folders to be displayed. 
This results in an empty tree if the source-folder is not contained on level 1 of the project-structure because the parent folder is filtered out. 

On the one hand this could be solved by switching to list-based interface collecting valid options upfront. But this contradicts the "create functionality" of the browsing interface.

On the other hand the filter could be tweaked to show parent-folders as well. This would present the structure. But then one has to make sure, that only leaf-nodes can actually be selected.

**Comment by lbeurerkellner** [comment]
After a discussion we agreed on the following changes:

**Project Dialog**
- The shown projects should be displayed as a list instead of a top level element only tree

**Source Folder Browse**
- The create functionality should be removed for the sake of simplification
- The available source folders should be displayed as a list of relative paths of the source folders. This also allows to support nested source folders
- Not existing source folders shouldn't be allowed. Project configuration/management is not part of the class/interface wizard what means it should be handled before opening the wizard.

**Module Specifier**
- No more virtual resources
- The dialog should only allow the creation of real file system folders.
- If the entered module name doesn't exist yet, it's not shown as a virtual resource.
- It's allowed to select files as well as folders. When selecting a file, its name should be put in the module name field.
- The text input should allow arbitrary path input. When opening the dialog with a non-existent path, a modal dialog should pop up, asking whether the user wants to create the non-existent part of the path on the file system.
  If he denies, the dialog pops back to the deepest path segment which exists. The module name isn't changed.

**Comment by lbeurerkellner** [comment]
The changes have been merged.
