### ISSUE TITLE
n4jsc.jar doesn't provide core runtime libraries and core libraries

### ISSUE THREAD

**Issue by dbo** [NumberFour/n4js#167]
In contrast to the IDE, the n4jsc.jar doesn't provide essential libraries when compiling. In effect developers have to provide resp. check out these manually.

This is usually about:
- n4js.lang (DI Injector)
- eu.numberfour.mangelhaft.assert (compiling tests)

Runtime libs:
- n4js-runtime-es2015
- n4js-runtime-esnext
- n4js-runtime-fetch
- n4js-runtime-n4
- n4js-runtime-v8
- n4js-runtime-node

However, in case the developer wants to compile with custom versions of these libraries, this should be possible, e.g.

``` bash
$ java -jar n4jsc.jar -t projects ./my-custom-n4js-runtime-es2015 ...
```

should take precedence over the the implicit `n4js-runtime-es2015` hosted by `n4jsc.jar`.

**Comment by lbeurerkellner** [comment]
Note that this means for now, that our integration tests that are based on N4JSC cannot rely on shipped code that was only changed in the eclipse/n4js repository. 

When modifying shipped code, all of the corresponding snapshot branches need to be updated as well. For integration tests, all shipped code has to be explicitly made available as a project location to N4JSC, otherwise the linking will not succeed.
