### ISSUE TITLE
Clean-up in grammar: keyword lists in N4JS.xtext and TypeExpressions.xtext should be consistent

### ISSUE THREAD

**Issue by mor-n4** [NumberFour/n4js#206]
We have several lists of keywords in both `N4JS.xtext` and `TypeExpressions.xtext`. This seems to be redundant and they seem to be defined inconsistently. It should be refactored such that there is only one set of such lists (probably in `TypeExpressions.xtext`) and those are used from both files.

The current inconsistency led to the problem in GH-203. This has been fixed for keyword `enum` (because it was a blocker for Daniel), but only a refactoring as described above would properly fix this for all cases.

**Comment by mor-n4** [comment]
in addition: we should probably allow "computed name" syntax in TStructMembers (otherwise we would not be able to define use-site structural types for all possible object literals, etc.)

similarly:  consider allowing strings as property names in TStructMembers

in general: the handling of member names in structural type expressions and classes / object literals should be consistent.

**Comment by mor-n4** [comment]
also rules for TStructMembers were now duplicated in n4js.xtext (they should only be in TypeExpressions.xtext)

**Comment by lbeurerkellner** [comment]
The rule TypeReferenceName in TypeExpressions.xtext should be in line with the idea of allowing N4Keywords as type names.

Consider following example:

```
class async {}

// Parser is confused by async keyword at this position
var f : (async) => number
// Parser is confused by async keyword at this position
var a : async
```

Despite the validity of the declaration of a class async, it is impossible to reference the resulting type in a TypeRef.

**Comment by lbeurerkellner** [comment]
Unfortunately allowing keywords in type reference names would make the grammar ambiguous due to the BogusTypeRefs. Consider the  following example:

```
class async {}
class A {
    async a() {}
}
```

This class could either declare an async method a or use the old type notation to declare a method with the return type async. This makes the language itself ambiguous.

A different issue is, that in addition to future and regular reserved keywords, the ECMA standard defines six special keywords (implements, package, protected, interface, private, public) which are forbidden, but only in strict mode. Since N4JS compiles to strict mode javascript, the following code sample won't run due to node complaining about the 'package' identifier:

```
class package {}
```
