### ISSUE TITLE
Add warning when function related type variable is not used in parameters or return type

### ISSUE THREAD

**Issue by JensN4** [NumberFour/n4js#234]
The following snippet stems from the SystemLoaderTest:

```
protected static <ThisT extends Object> init(that: Object): Object {
      ...
     let mod = ...;
     return new (mod as constructor{ThisT})();
    }
```

That doesn't make any sense: ThisT is not used in the formal parameters nor in the return type. So it makes no sense to have it here at all. Maybe it should even be an error?

Acceptance Criteria:

```
// XPECT FIXME warnings --> "Type variable T not used in parameters or return type." at "T"
function <T> f1(s: string): void {}

// XPECT nowarnings -->
function <T> f2(s: T): void {}

// XPECT nowarnings -->
function <T> f3(s: Array<T>): void {}

class C<S> {
    // XPECT nowarnings -->
    m1(s: string): void {}

    // XPECT FIXME warnings --> "Type variable T not used in parameters or return type." at "T"
    <T> m2(s: T): void {}

    // XPECT nowarnings -->
    <T> m2(s: Array<T>): void {}

    // XPECT FIXME warnings --> "Type variable S not used in parameters or return type." at "S"
    static <S> s1(s: string): void {}

    // XPECT nowarnings -->
    static <S> s2(s: S): void {}

    // XPECT nowarnings -->
    static <S> s3(s: Array<S>): void {}

}

```

**Comment by kduske-n4** [comment]
There is one particular case where I have opted to drop a warning after discussing it with @mor-n4. Consider the following example taken from `/eu.numberfour.n4js.xpect.tests/model/typesystem/Generics_TypeArgumentChecks_TypeVarInUpperBound1.n4js.xt`:

```
function <T1, T2 extends T1> foo() {}
```

In this function declaration, one could argue that both generic type parameters `T1` and `T2` are unused since no parameter or return type refers to either of them. On the other hand, `T1` is used in the generic type parameter list, so one could also argue that is is being used. I have opted to implement the latter interpretation so that only `T2` has a warning attached.
