### ISSUE TITLE
N4JS's discussion group has no markdown capability

### ISSUE THREAD

**Issue by shelby3** [NumberFour/n4js#265]
I created a new topic there to explain why Google Groups is not desirable IMO:

https://groups.google.com/forum/#!topic/n4js/mb4HArUcpVk

Thus I will create issues here for the issues I want to discuss, rather than create topics at Google Groups.

**Comment by JensN4** [comment]
We use github issues for bugs and feature requests. We have a project board to track our work, and I (as the project manager) also use that for statistics (e.g., how many issues did we close in the last sprint). Using issues for arbitrary discussions is possible, but it would complicate the project management, since I always have to filter out discussions. Thus I would appreciate everybody to use the google group for discussions, even if it lacks some formatting features.

**Comment by shelby3** [comment]
@JensN4 I understand your point about mucking up statistics and other aspects by conflating the Issues board with a discussion board. Github really needs to enable more than one Issues board, so we can track them separately.

This problems with Google Groups reach beyond just lack of markdown. It is that Github also inserts cross-references into the Issues threads, which facilitates finding all the related discussions inter alia. And it allows me to easily see the Github identities of commentators.

I suggest you could create another Github repository (project) name for another Issues tracking dedicated to discussion. Or you could use the discussion hosted software Rust is using, but really I think Github's is superior in my experience thus far.

I avoid Google Groups like the plague now. I will post for something very important, but will quickly try to transition any discussion away from there.

However, if your unstated (or implied) motivation (and no accusation or presumption is intended) is to obscure or distance discussion that would be defocusing to driving interest in and development, then my suggestion is countervailing.
