### ISSUE TITLE
search PATH for 'node' instead of assuming default path

### ISSUE THREAD

**Issue by meysholdt** [NumberFour/n4js#334]
Currently, 
`eu.numberfour.n4js.binaries.nodejs.NodeBinariesConstants.BUILT_IN_DEFAULT_NODE_PATH`
assumes `node` in `/usr/local/bin/` when no system property is configured.

When following https://github.com/nodesource/distributions#debinstall, `node` gets installed into `/usr/bin/` and `NodeBinariesConstants` doesn't find it.

It would be nice if `NodeBinariesConstants` would search the PATH variable for the first `node` binary it finds and use that binary. This would require less tedious configuration to get the tests running. 

There is a nice code snippet in http://stackoverflow.com/a/23539220 on how to do this.

**Comment by yoosiba** [comment]
I am a bit surprised that using VM setting (```eu.numberfour.n4js.defaultNodePath```) or environment setting (```NODEJS_PATH```) was too tedious. Still I have refactored node defaults lookup (6b5f9453e11af1f29e8d40e124d66bb79a177070).

Now, in addition to those checks lookup will parse ```PATH``` and if that fails it will invoke ```which node``` (or ```where node.exe``` depending on OS). Only if those lookups fail it will fallback to ```/user/local/bin``` (or ```C:\Program Files\nodejs```).

Note that those two OS depended lookups have "known" issue on *nix systems. They work fine if you start your Eclipse/N4JSIDE from terminal (i.e. shell with your user config). When you start them from GUI (e.g. finder on OSX, Unity on Ubuntu) running eclipse platform is not inheriting your default shell configuration. 
While I have seen this behaviour for a while I haven't found solution for it. Also since there are VM and ENV settings that override this anyway, and dedicated preference page in the N4JSIDE (that overrides all above) this is not high priority to dig into that problem. 

I am closing this issue. If you have an advice on path/profile/shell settings when spawning external process from eclipse please provide them in separate (new) ticket.

**Comment by meysholdt** [comment]
thank you! The more situations in which no manual configuration is needed, the better, I think :)
