### ISSUE TITLE
Unnecessary warnings for computed property names in Object types, Object literals, any types, or ~Object

### ISSUE THREAD

**Issue by arrowplum** [NumberFour/n4js#384]
Since `Object`'s and `any`'s fields are not typed anyway, this should have no warning
note: I forget the noWarnings syntax but put it in there so you see what I am talking about

``` javascript

var thing: string;
thing = "hi";

var o: Object;
//XPECT noWarnings --> "Computed property name using an expression other than a compile-time expression; this property won't be type-checked at compile time."
o = {
    [thing]: 3
}

const cO = {
    [thing]: 3
}

cO
```

marking as prio-high as the warnings are numerous and hide legit warnings.

**Comment by mor-n4** [comment]
At least if the type of `o` is dynamic, this seems to make sense

If type of `o` is `Object`, then the current behavior (showing a warning) is inconsistent with the index access:
```javascript
var thing: string;
thing = "hi";

var o: Object;
//XPECT noWarnings --> "Computed property name using an expression other than a compile-time expression; this property won't be type-checked at compile time."
o = {
    [thing]: 3 // <-- shows warning
}
o[thing] = 3; // <-- does *not* show warning
```
HOWEVER, as part of IDE-2523 we will probably restrict the "anything goes" index access (i.e. index access with an index expression that is not a compile-time expression) to dynamic types (i.e. no longer accepting plain Objects), so maybe we should not change this now because it will have to be changed back later.

If type of `o` is `any` we probably want to keep the warning as is.

BUT: all the above is just a first guess and has to be reconsidered.

**Comment by mmews-n4** [comment]
continued here https://github.com/eclipse/n4js/issues/549
