### ISSUE TITLE
Spec constructor does not initialize fields inherited from structural interfaces.

### ISSUE THREAD

**Issue by aschaefer-n4** [NumberFour/n4js#388]
**Spec constructor does not initialize fields inherited from structural interfaces. Consider the following example:**
```typescript
export public interface ~MyInterface {
    public second: boolean;
}

export public class MyClass implements MyInterface {
    public first: boolean;
    public constructor(@Spec spec: ~i~this) {}
}

let obj = { first: true, second: true } as MyClass;
let instance = new MyClass(obj);

console.log(instance);
```
**Output:**
`MyClass { first: true }`

**Now, removing the tilde sign and changing the the interface type to non-structural works fine:**
```typescript
export public interface MyInterface {
    public second: boolean;
}
```
**Output:**
`MyClass { first: true, second: true }`

**The difference in the generated code seems to be the following line:**
`MyInterface.$fieldInit.call(this, spec, {});`

**Comment by mor-n4** [comment]
probably an issue in the transpiler: the invocation of the `$fieldInit` function is not generated in the constructor of a class (e.g. `MyClass`) for implemented interfaces, if they are def-site structural. This makes sense, because def-site structural interfaces must not have field initializer expressions (there's a validation in place). But the `$fieldInit` function is also used for spec-ctor handling. Thus, invocation of the `$fieldInit` function should be generated also for def-site structural interfaces. This would be a simple change in `eu.numberfour.n4js.transpiler.es.assistants.ClassConstructorAssistant.createDelegationToFieldInitOfImplementedInterfaces(N4ClassDeclaration, FormalParameter)`.

(but all this is just a quick guess; needs to be double-checked!)

**Comment by qtran-n4** [comment]
I am currently looking into this bug.
