### ISSUE TITLE
Don't allow passing primitive types as spec object and for structural types in general

### ISSUE THREAD

**Issue by NumberFourAG** [NumberFour/n4js#4]
IDEBUG-58

```
class A {
    constructor(@Spec ~~this spec) {
    }
}
new A("hello"); // should be an error
```

So passing primitive types like 
- boolean
- number
- string
- pathSelector
- i18nKey
- typeName
  as well as virtual types like EnumBaseType shouldn't be allowed. 
  All other built-in types even null and undefined are still allowed.

This task can probably extended to a general validation that primitives are not compatible to structural types in general. This should be easy to add in the type system.

**Comment by yoosiba** [comment]
also see _no checks on primitive value property access_ #262

**Comment by JensN4** [comment]
Additional XPect test:

```
class C {
	public s: int? = 42;
}

// XPECT noerrors -> 
var c1: ~C = {};
// XPECT FIXME errors -> "int is not a subtype of ~C." 
var c2: C = 2;

c1;c2;

class D {
	public s: int;
}

// wrong error message at the momen XPECT FIXME errors -> "int is not a subtype of ~D." 
var d1: ~D = 42;

d1;
```

**Comment by lbeurerkellner** [comment]
Same problem in this issue: **primitive types should not be subtypes of structural types ~Object and ~~Object** (https://github.com/NumberFour/n4js/issues/369) 

Also note that this issue causes this snippet to be valid N4JS code:

```
var a : ~int = new Object();
console.log(a.toFixed(2));
```

This obviously results in a runtime error.

From a user perspective the idea of structural primitive types is not really defined. However, this is used internally whenever we use a structural type variable with a generic type that was parameterised by a primitive type.

**Comment by lbeurerkellner** [comment]
After a discussion with @mor-n4 we decided on a first solution which includes the following measures:

* allow ~any, ~int, etc. 
  **RATIONALE**: all structural types are objects; ~int represents the auto-boxed int value
* ~any, ~int, ... are all equivalent to any
* adjust auto-boxing rules to NOT apply auto boxing in cases like:

  ```
  let ns: ~number = {};
  ns.toFixed(3); // <-- do not apply auto boxing here; should show "No such member toFixed"
  ```
  This is to prevent runtime exceptions, since `{}` doesn't have the method `toFixed` but for now this snippet is valid N4JS code.

After having implemented this, I will reconsider new and existing subtype relations introduced by this.

**Comment by qtran-n4** [comment]
@lbeurerkellner : What do you mean with _allow ~any, ~int, etc._? Allow to what?

**Comment by qtran-n4** [comment]
sorry accidentally pressed the close button :)

**Comment by lbeurerkellner** [comment]
For now, the structural type operator `~` can be used with non-object types like `any`, `int`etc. 

Since structural typing operates on a member level, the use of the operator with non-object types is questionable. However, it is possible if we assume that primitive types are just objects without any members. So basically you can write code like:

```
var a : ~int = {};
```

Only that the variable a is not very useful, since the type `~int` doesn't have any members (is equivalent to any). So in a first solution we want to allow the use of the operator in this way although it might not make a whole lot of sense for a user.

**Comment by lbeurerkellner** [comment]
While further investigating this task I came across the following issue:

```
// Converts a structural type to its non-structural counterpart 
function <T> convertToNonStructural(a : ~T) : T {
	return a;
}

class A {
	private m() {
		console.log("This is a genuine A instance")
	}
	f : int
}

// Let's create some fake A instances
var a = <A> convertToNonStructural({f : 3});

// This is a genuine A, isn't it?
a.m();
```

The code compiles without any problems. Only at runtime, it will fail, since a doesn't reference a genuine A instance at all. 

This is possible because of a special case in the type system, which leads to the structural type operator (~) being ignored for TypeVariables.

**Comment by qtran-n4** [comment]
Using @lbeurerkellner 's trick, we can break the soundness of our type system:

```
class C<T> {
	private m1: T;
	private m2: ~T;
	
	public try() {
		this.m2 = this.m1;   // for all T, T <: ~T  -> OK
		this.m1 = this.m2;  // for all T, ~T <: T  -> not OK
	}
} 
```

@lbeurerkellner BTW shouldn't we move this issue to https://github.com/eclipse/n4js ?

**Comment by mor-n4** [comment]
@lbeurerkellner this is a bug. Good find!
Please fix together with this ticket (because it seems like a 1 line fix and is closely related; if more work, create separate ticket).
