### ISSUE TITLE
implementing structural interface does not set fields in spec constructor

### ISSUE THREAD

**Issue by arrowplum** [NumberFour/n4js#401]
```typescript
interface ~IThing {
    public dog: string;
}

class SomeThing implements IThing {
    public constructor(@Spec spec:~i~this) {}
}

//let st = new SomeThing({}) //correctly errors '~Object is not a structural subtype of ~i~SomeThing: missing field dog; dog failed: non-optional writable field requires a readable field or a getter in subtype.'

let st2 = new SomeThing({dog:"barker"})

console.log(st2.dog)
```

If you look at the compiled output, you see that the field initializers are not called (although they are there)

```javascript
		SomeThing = function SomeThing(spec) {
			if (spec) {}
		};
```

if you make the interfacce non-structural the initializer is called 

```javascript
		SomeThing = function SomeThing(spec) {
			if (spec) {}
			IThing.$fieldInit.call(this, spec, {});
		};
```

I would recommend this to be high priority because it adds subtle bugs in the code where fields are not being initialized as would be expected if they originate in structural interfaces.

**Comment by mor-n4** [comment]
quick note:
the filter at the beginning of method `ClassConstructorAssistant#createDelegationToFieldInitOfImplementedInterfaces()` is causing this behavior (i.e. call to `$fieldInit` not generated for structural interfaces).

Simply removing this filter would "fix" the problem. However, before doing that, it needs to be carefully investigated why this filter was added in the first place. Maybe the only motivation was this: since fields of structural interfaces are not allowed to have initializer expressions, it is not necessary to call `$fieldInit` for structural interfaces (but this is probably wrong, because `$fieldInit` also handles initialization of fields from a spec ctor's spec object).

**Comment by arrowplum** [comment]
Also,  $fieldInit is being generated but is just never being called in this
case.

**Comment by arrowplum** [comment]
found this older bug that has not been fixed https://github.com/NumberFour/n4js/issues/388

**Comment by arrowplum** [comment]
marking as a dupe but raising prio
