### ISSUE TITLE
binding with use site structural types is ignoring structural type during injection

### ISSUE THREAD

**Issue by NumberFourAG** [NumberFour/n4js#44]
IDEBUG-498

```
@Bind(~A, ~B)
@Binder class UseSiteStructToUseSiteStruct{}

@GenerateInjector
@UseBinder(UseSiteStructToUseSiteStruct)
class DIC5{
    @Inject ~A a1; // B
    @Inject A a2; // A
}

class Test {
       @Test 
    void testFieldInjectionOfUseSiteStructTypesWithUseSiteStructType() {
        // TODO Jakub -- @UseBinding should to the trick already
        var dic =  N4Injector.of(DIC5,null,UseSiteStructToUseSiteStruct).create(DIC5);
        DIAsserts.equalsClassName(dic, "DIC5");
        console.log(dic.a1.m());
        console.log(dic.a2.m());
        Assert.equal(dic.a1.m(), "B");
        Assert.equal(dic.a2.m(), "A");
    }
}
```

See /runtime-env.es5.tests/test/n4js/n4/di/FieldInjStructTypes.n4js (test is ignored at the moment)
Also review spec!

**Comment by mor-n4** [comment]
our first intention was to disallow structural types in DI altogether. However, we noticed that there was an earlier request to introduce support for it (see IDEBUG-418).
Conclusion after some discussion: there might be the following cases where structural types for DI are required:
1. if there is a definition-site structural type and the developer wants to use it with `@Inject`. This could be solved by allowing definition-site structural types only; distinction of structural vs. non-structural in the bindings would not be required.
2. when dealing with given types that cannot be altered (e.g. from libraries) and the dev wants to inject values of one type A for another type I of which A is a subtype only structurally.
   
   ```
   // Library 1
   
   class A {
   public get name(): string {return "name";}
   public set name(n: string) {}
   }
   
   // Library 2
   
   interface I {
   public name: string;
   }
   
   class C {
   // use case #1:
   @Inject
   public value: ~I;
   }
   
   
   // client code
   
   @GenerateInjector
   class Main {
   
   @Inject
   myC: C;
   
   // use case #2:
   @Inject
   public value: ~I;
   }
   
   @Bind(I,A) // <-- cannot and should not be allowed
   @Bind(~I,A) // <-- could be allowed
   @Binder class MyBinder {}
   ```
   
   This scenario requires distinction of structural vs. non-structural types in the DI bindings (i.e. at first argument of `@Bind` annotation) because otherwise it is not possible to allow the binding `@Bind(I,A)` because A is not a nominal subtype of I.

This has to be discussed further, so I will set this issue back to "open".
