### ISSUE TITLE
Content assist displays all public variables when in 'this' context. Also it does not respect capitalization.

### ISSUE THREAD

**Issue by NumberFourAG** [NumberFour/n4js#60]
IDEBUG-625
 If you are in a class method and start accessing a member with `this.xx` content assist will show you all possible global completions that start with your prefix after `this` case insensitive.

Probably easiest to look at the animated gif.

![ide_content_assist](https://cloud.githubusercontent.com/assets/20302628/18045997/0a1f5a96-6dd6-11e6-9309-1b45db50c021.gif)

**Comment by kduske-n4** [comment]
Note that these bogus proposals only show up if the class is exported.

**Comment by kduske-n4** [comment]
The correct proposals are collected when Xtext processes a (grammar) property assignment to a property called _property_ which belongs to the grammar rule `ParameterizedPropertyAccessExpression`. This appears to be in accordance with the current cursor position in the source code (`this.n|`) when the completion proposals are requested, since the (partial) expression `this.n` might be a property access expression.

The wrong proposals hail from the method `AbstractTypeExpressionsProposalProvider#completeParameterizedTypeRefNominal_DeclaredType` which is called during processing a (grammar) property assignment to a property named _declaredType_ which belongs to the grammar rule `ParameterizedTypeRef`. However, we could not determine why Xtext believes that that particular rule might apply when parsing the expression `this.n`. It seems to be an error either in Xtext (maybe related to fragments, since the `ParameterizedPropertyAccessExpression` rule uses fragments) or in our grammar.

We have applied a fix by adding a check to the scoping provider that is used during content assist proposal retrieval. `completeParameterizedTypeRefNominal_DeclaredType` calls `lookupCrossReference`, and at some point, the scope of the reference to be looked up is determined using `N4JSScopeProvider#getScopeForContentAssist`. It turns out that the type of the given context, in this case `ParameterizedPropertyAccessExpression` does not conform to the reference's container type, which is `ParameterizedTypeRef`. To us, this indicates that this request is bogus and we now return a null scope.

Even though the original error no longer turns up, we should try and determine why the assignment to _declaredType_ of the grammar rule `ParameterizedTypeRef` is called at some point.
