### ISSUE TITLE
Nested nameless FunctionExpression´s do not compile (NPE) or are mapped to FunctionDeclaration

### ISSUE THREAD

**Issue by NumberFourAG** [NumberFour/n4js#88]
IDEBUG-731
 If nameless nested function expressions are encountered in a block (e.g. other function-declaration) the code breaks.  

Note this xpect-file is not compiling unless the lines marked with TODO are commented out.

```

function doExec(arg: {function():void}) {
    arg();
}

function a () {

    function a1():void{ return ; } // works
    function a2(){ return ; } // works
    function a3(){ return null; } // works
    function a4(){ } // works 

    var a5 = function a5(){console.log("x0")};
    doExec(a5); // works

    (function ():void{ console.log("x1"); return ; })() // works
    doExec( function ():void{ console.log("x2"); return ; }  ) //  works    

    var f1 = function ():void{ return ; } // works
    var f2 = function (){ return ; } // works
    var f3 = function (){ return null; } // works
    var f4 = function (){ } // works    

    // START of problematic section:

    // TODO shows no errors  - but doesn't compile (NPE) :
        // XPECT FIXME errors --> "function expressions must have a name or have to be directly invoked." at "function ():void{ return ; }" 
    function ():void{ return ; }  

        // X!PECT FIXME noerrors -->  "Return statement must have an expression of type null" at "return ;"
        // XPECT FIXME errors --> "function expressions must have a name or have to be directly invoked." at "function (){ return ; }" 
    function (){ return ; } // see fixme above

    // TODO shows no errors  - but doesn't compile (NPE) :
        // XPECT FIXME errors --> "function expressions must have a name or have to be directly invoked." at "function () { return null; }" 
    function (){ return null; } 

    // XPECT FIXME noerrors --> "Missing return or throw statement (all control flows must terminate with an return value or be aborted)." at "function (){ }"
        // XPECT FIXME errors --> "function expressions must have a name or have to be directly invoked." at "function (){}" 
    function (){ }  

} ;

a();

```

The code snippets above are actually invalid syntax. Currently our grammar allows FunctionDeclarations to have no name.( ES6 requires always a name for FunctionDeclarations, except for {{export default}} declared function-declarations.) Hence our relaxed grammar simply goes the way to parse a function-declaration were only a function-expression is allowed. 
Because of that subsequent code renders NPEs. 

If it were correctly parsed to a function-expression, the expression itself (without a name) cannot be referred from other parts of the code and therefore would be +dead code+. This is no valid ES6 (at least Babel complains). At least two options are viable at that point:
- the user assigns the FE to a variable
- the user directly invokes the code by wrapping the FE into parenthesis and directly executes it (another pair of parenthesis) 
  --> this should be reported by an validation.

**Comment by torstenkraemer** [comment]
The problematic parts in the example given above are actually correctly _not_ parsed as function expression. C.f.  http://www.ecma-international.org/ecma-262/6.0/index.html#sec-expression-statement stating:
`Also, an ExpressionStatement cannot start with the function or class keywords because that would make it ambiguous with a FunctionDeclaration, a GeneratorDeclaration, or a ClassDeclaration.`.

Also taken from our spec, "6.2.1 Function Declaration", p. 161f. stating "In contrast to plain JavaScript, function declarations can be used in blocks in N4JS". 

So I think introducing a validation for missing names is sufficient here. Showing an error here then subsequently will prevent transpilation and the NPE will not show up.

By the way, the type-system errors documented in this error report have already been solved.

**Comment by torstenkraemer** [comment]
merged.
