### ISSUE TITLE
dependant initialized fields in interfaces do not work because they are done out of order

### ISSUE THREAD

**Issue by NumberFourAG** [NumberFour/n4js#94]
IDEBUG-785
 The following n4js test fails because `fu.blahHaver.blah` is  `undefined`:

``` javascript
interface IFu {
    public blah = "blarhg";
    public blahHaver = {blah:this.blah};
}
class Fu implements IFu{
    constructor() {

    }
}

export public class TestUm {
    @Test
    blahTest() {
        var fu = new Fu();
        Assert.strictEqual(fu.blahHaver.blah, fu.blah);
    }
}
```

**Comment by mor-n4** [comment]
for principal reasons, we cannot guarantee that the implementations will follow the same order of fields in the interface (implemenation of multiple interfaces with fields of same name, etc.)
therefore we must disallow "this" in init expr of fields in interfaces (see #124)
then, this issue is obsolete

--> closing this as duplicate
